### PR TITLE
fr.json

### PR DESCRIPTION
**Pull request by christelleleroy92**
This is the Website French translation

### CODE REVIEW

**Comment by exploshot** [comment]
DECLINED. 
Please submit it as ```fr.json```

**Review by nnian — COMMENTED** [review]
please rename your "Update fr.json" to "fr.json"

Thank you

**Comment by christelleleroy92** [comment]
Hello,

I have renamed the file into fr.json, my username in translation spreadsheet is christelle92

**Comment by exploshot** [comment]
You have renamed the PR but not the file.

**Comment by christelleleroy92** [comment]
Please check now

**Comment by Sw0rdf1sh1** [comment]
> Please check now

file is correct but, now it's in a wrong folder. Please move it back to i18n/fr.json

**Comment by christelleleroy92** [comment]
Hello sir, could you check now please?

**Pull request merged**
